# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-01 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import products.models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200731_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(location='protected'), upload_to=products.models.upload_product_file_loc),
        ),
    ]
