# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-28 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200728_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='order_id',
            field=models.CharField(max_length=120),
        ),
    ]
