# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-29 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200728_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPurchaseManger',
        ),
    ]
