# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-26 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectviewed',
            name='content',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
