# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-26 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_objectviewed_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectviewed',
            name='content',
        ),
        migrations.AlterField(
            model_name='objectviewed',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='contenttypes.ContentType'),
        ),
    ]
